version: "3.8"
services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: redis_container

  db:
    image: postgres
    container_name: postgres_db_container
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=test1
      - POSTGRES_USER=test1
      - POSTGRES_PASSWORD=test1


  app:
    build: .
    volumes:
      - .:/project_dir
    ports:
      - 8000:8000
    image: app:project_dir
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis


  celery:
    build:
      context: .
    command: celery -A core worker -l DEBUG
    volumes:
      - .:/project_dir
    depends_on:
      - db
      - redis
      - app




