version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/project_dir
    ports:
      - 8000:8000
    image: app:project_dir
    container_name: main_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db_container
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=test1
      - POSTGRES_USER=test1
      - POSTGRES_PASSWORD=test1


